=== davidfdezc/vnx/vnx-folder/data/dynamips.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="hw">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="chassis" type="xs:string" minOccurs="0" />
        <xs:element name="slot" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute name="id" type="xs:string" />
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="console_base" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="port" type="xs:string" />
          </xs:complexType>
        </xs:element>
        <xs:element name="console" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="port" type="xs:string" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="vnx_dynamips" >
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="hw" />
        <xs:element name="global">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="sparsemem" type="xs:string" minOccurs="0" />
              <xs:element name="ghostios" type="xs:string" minOccurs="0" />
              <xs:element ref="hw" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="vm">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="conf" type="xs:string" minOccurs="0"  />
              <xs:element ref="hw" minOccurs="0" maxOccurs="unbounded" />
              <xs:element name="login" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="password" type="xs:string" />
                  <xs:attribute name="user" type="xs:string" />
                </xs:complexType>
              </xs:element>
              <xs:element name="enable" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="password" type="xs:string" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" />
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== davidfdezc/vnx/vnx-folder/data/simple_dynamips-dn.xml
<?xml version="1.0" encoding="UTF-8"?>

<vnx_dynamips xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
     xsi:noNamespaceSchemaLocation="/usr/share/xml/vnx/dynamips.xsd"> 

  <global>
    <sparsemem>true</sparsemem>
    <ghostios>false</ghostios>
    <hw>
       <slot id="0">NM-4E</slot>
       <slot id="1">NM-4T</slot>
       <console_base port="1000"/>
     </hw>

  </global>


  <vm name="R1">
     <!--conf>/home/jrodriguez/R1.txt</conf-->
     <hw>
       <chassis>c3640</chassis>
       <slot id="0">NM-4E</slot>
       <slot id="1">NM-4T</slot>
       <console port="920"/>
     </hw>
     <login password="cosas"/>
     <login user="jack_sparrow" password="perla_negra"/>
     <login user="caribe" password="piratas"/>
     <enable password="xxxx"/>
  </vm>

  <vm name="R2">
	<conf>/home/jrodriguez/R2.conf</conf>
	<login password="cosas"/>
  </vm>
    <vm name="R3">
  	</vm>

</vnx_dynamips>

=== davidfdezc/vnx/vnx-folder/data/tutorial_root1_ubuntu_dynamips-dn.xml
<?xml version="1.0" encoding="UTF-8"?>

<vnx_dynamips xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
     xsi:noNamespaceSchemaLocation="/usr/share/xml/vnx/dynamips.xsd"> 

  <global>
    <sparsemem>true</sparsemem>
    <ghostios>false</ghostios>
    <hw>
       <slot id="0">NM-4E</slot>
       <slot id="1">NM-4T</slot>
     </hw>
  </global>


  <vm name="r1">
     <conf>conf/r1.conf</conf>
     <login user="root" password="xxxx"/>
     <enable password="xxxx"/>
  </vm>

  <vm name="r2">
     <conf>conf/r2.conf</conf>
     <login user="root" password="xxxx"/>
     <enable password="xxxx"/>
  </vm>

</vnx_dynamips>

=== davidfdezc/vnx/vnx-folder/data/simple_dynamips2-dn.xml
<?xml version="1.0" encoding="UTF-8"?>

<vnx_dynamips xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
     xsi:noNamespaceSchemaLocation="/usr/share/xml/vnx/dynamips.xsd"> 

  <global>
    <sparsemem>true</sparsemem>
    <ghostios>false</ghostios>
    <hw>
       <npe>200</npe>
       <slot id="0">C7200-IO-2FE</slot>
       <slot id="1">PA-2FE-TX</slot>
     </hw>

  </global>

  <vm name="cisco2">
     <conf>conf/cisco2.conf</conf>
     <hw>
       <chassis>c7200</chassis>
       <npe>400</npe>
       <slot id="0">C7200-IO-2FE</slot>
       <slot id="1">PA-2FE-TX</slot>
     </hw>
     <!--login password="xxxx"/-->
     <login user="root" password="xxxx"/>
     <enable password="xxxx"/>
  </vm>
  
</vnx_dynamips>
