=== davidfdezc/vnx/vnx-folder/data/vnx-2.00.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--

VNX Virtual Scenarios Definition Language v2.00

Virtual Networks over LinuX (VNX) Project 
www:    http://www.dit.upm.es/vnx 
e-mail: vnx@dit.upm.es 

-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <xs:element name="automac">
    <xs:complexType>
      <xs:attribute default="0" name="offset" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="basedir">
    <xs:complexType mixed="true"/>
  </xs:element>

  <xs:element name="bw">
    <xs:complexType mixed="true"/>
  </xs:element>

  <xs:element name="cmd-seq">
    <xs:complexType mixed="true">
      <xs:attribute name="seq" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="conf">
    <xs:complexType mixed="true"/>
  </xs:element>

  <xs:element name="console">
    <xs:complexType mixed="true">
      <xs:attribute name="id" type="xs:string" use="required"/>
      <xs:attribute name="display" type="xs:string" use="optional"/>
      <xs:attribute name="port" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="dynamips_ext">
    <xs:complexType mixed="true"/>
  </xs:element>

  <xs:element name="exec">
    <xs:complexType mixed="true">
      <xs:attribute name="user" type="xs:string" use="optional"/>
      <xs:attribute name="seq" type="xs:string" use="required"/>
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="verbatim"/>
            <xs:enumeration value="file"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="ostype" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="system"/>
            <xs:enumeration value="exec"/>
            <xs:enumeration value="xsystem"/>
            <xs:enumeration value="xexec"/>
            <xs:enumeration value="cmd"/>
            <xs:enumeration value="show"/>
            <xs:enumeration value="set"/>
            <xs:enumeration value="load"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="seq_help">
    <xs:complexType mixed="true">
      <xs:attribute name="seq" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="exec_mode">
    <xs:complexType mixed="true">
      <xs:attribute name="type" type="xs:string" use="required"/>
      <xs:attribute name="subtype" type="xs:string" use="optional"/>
      <xs:attribute name="os" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="extension">
    <xs:complexType>
      <xs:attribute name="conf" type="xs:string" use="required"/>
      <xs:attribute name="plugin" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="filesystem">
    <xs:complexType mixed="true">
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="direct"/>
            <xs:enumeration value="cow"/>
            <xs:enumeration value="hostfs"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="filetree">
    <xs:complexType mixed="true">
      <xs:attribute name="seq" type="xs:string" use="required"/>
      <xs:attribute name="root" type="xs:string" use="required"/>
      <xs:attribute name="user" type="xs:string" use="optional"/>
      <xs:attribute name="group" type="xs:string" use="optional"/>
      <xs:attribute name="perms" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="forwarding">
    <xs:complexType>
      <xs:attribute default="ip" name="type" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="ip"/>
            <xs:enumeration value="ipv4"/>
            <xs:enumeration value="ipv6"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="global">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="version"/>
        <xs:element ref="scenario_name"/>
        <xs:element minOccurs="0" ref="ssh_version"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="ssh_key"/>
        <xs:element minOccurs="0" ref="automac"/>
        <xs:element minOccurs="0" ref="netconfig"/>
        <xs:element ref="vm_mgmt"/>
        <xs:element minOccurs="0" ref="tun_device"/>
        <xs:element minOccurs="0" ref="vm_defaults"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="cmd-seq"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="extension"/>
        <xs:element maxOccurs="1" minOccurs="0" ref="dynamips_ext"/>
        <xs:element maxOccurs="1" minOccurs="0" ref="olive_ext"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="help"/>        
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="group">
    <xs:complexType mixed="true"/>
  </xs:element>

  <xs:element name="help">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="seq_help"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="host">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="hostif"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="physicalif"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="route"/>
        <xs:element minOccurs="0" ref="forwarding"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="exec"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="host_mapping" type="xs:string"/>

  <xs:element name="hostif">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="vlan"/>	
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="ipv4"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="ipv6"/>
      </xs:sequence>
      <xs:attribute name="net" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="if">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="vlan"/>	
        <xs:element minOccurs="0" ref="mac"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="ipv4"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="ipv6"/>

      </xs:sequence>
      <xs:attribute name="net" type="xs:string" use="required"/>
      <xs:attribute name="id" type="xs:string" use="required"/>

      <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="ipv4">
    <xs:complexType mixed="true">
      <xs:attribute default="255.255.255.0" name="mask" type="xs:string" use="optional"/>
      <xs:attribute default="primary" name="type" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="ipv6">
    <xs:complexType mixed="true">
      <xs:attribute name="mask" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="vlan">
    <xs:complexType>
     <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="tag"/>	
     </xs:sequence>
    <xs:attribute name="trunk" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>

 <xs:element name="tag">
    <xs:complexType>
      <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="kernel">
    <xs:complexType mixed="true">
      <xs:attribute name="root" type="xs:string" use="optional"/>
      <xs:attribute name="devfs" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="mount"/>
            <xs:enumeration value="nomount"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="modules" type="xs:string" use="optional"/>
      <xs:attribute name="initrd" type="xs:string" use="optional"/>
      <xs:attribute default="off" name="trace" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="on"/>
            <xs:enumeration value="off"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="mac">
    <xs:complexType mixed="true"/>
  </xs:element>

  <xs:element name="mem">
    <xs:complexType mixed="true"/>
  </xs:element>

  <xs:element name="mgmt_net">
    <xs:complexType>
      <xs:attribute name="net" type="xs:string" use="optional"/>
      <xs:attribute name="managed" type="xs:string" use="optional"/>
      <xs:attribute name="config" type="xs:string" use="optional"/>
      <!--xs:attribute name="sock" type="xs:string" use="required"/>
      <xs:attribute name="hostip" type="xs:string" use="required"/>
      <xs:attribute name="autoconfigure" type="xs:string" use="optional"/-->
    </xs:complexType>
  </xs:element>

  <xs:element name="mng_if">
    <xs:complexType mixed="true"/>
  </xs:element>

<xs:element name="connection">
    <xs:complexType>
       <xs:sequence>
          <xs:element minOccurs="0" ref="vlan"/>  
   </xs:sequence>
      <xs:attribute name="net" type="xs:string" use="required"/>
      <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="net">
    <xs:complexType>
      <xs:sequence>
        <xs:element  minOccurs="0" ref="bw"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="connection"/>
      </xs:sequence>
      <xs:attribute name="capture_dev" type="xs:string" use="optional"/>
      <xs:attribute name="sock" type="xs:string" use="optional"/>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="uml_switch_binary" type="xs:string" use="optional"/>
      <xs:attribute name="vlan" type="xs:string" use="optional"/>
      <xs:attribute name="capture_file" type="xs:string" use="optional"/>
      <xs:attribute name="controller" type="xs:string" use="optional"/>
      <xs:attribute name="of_version" type="xs:string" use="optional"/>
      <xs:attribute name="mode" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="virtual_bridge"/>
            <xs:enumeration value="uml_switch"/>
            <xs:enumeration value="openvswitch"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute default="yes" name="managed" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="yes"/>
            <xs:enumeration value="no"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="external" type="xs:string" use="optional"/>
      <xs:attribute default="no" name="hub" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="yes"/>
            <xs:enumeration value="no"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute default="lan" name="type" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="lan"/>
            <xs:enumeration value="ppp"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="capture_expression" type="xs:string" use="optional"/>
      <xs:attribute default="no-shared" name="scope" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="shared"/>
            <xs:enumeration value="no-shared"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="netconfig">
    <xs:complexType>
      <xs:attribute default="on" name="promisc" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="on"/>
            <xs:enumeration value="off"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute default="off" name="stp" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="on"/>
            <xs:enumeration value="off"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="olive_ext">
    <xs:complexType mixed="true"/>
  </xs:element>

  <xs:element name="on_boot">
    <xs:complexType mixed="true"/>
  </xs:element>

  <xs:element name="physicalif">
    <xs:complexType>
      <xs:attribute name="mask" type="xs:string" use="optional"/>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute default="ipv4" name="type" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="ipv4"/>
            <xs:enumeration value="ipv6"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="gw" type="xs:string" use="optional"/>
      <xs:attribute name="ip" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="route">
    <xs:complexType mixed="true">
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="ipv4"/>
            <xs:enumeration value="ipv6"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="gw" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="shell">
    <xs:complexType mixed="true"/>
  </xs:element>

  <xs:element name="scenario_name">
    <xs:complexType mixed="true"/>
  </xs:element>

  <xs:element name="ssh_key">
    <xs:complexType mixed="true"/>
  </xs:element>

  <xs:element name="ssh_version">
    <xs:complexType mixed="true"/>
  </xs:element>

  <xs:element name="tun_device">
    <xs:complexType mixed="true"/>
  </xs:element>

  <xs:element name="user">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="group"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="ssh_key"/>
      </xs:sequence>
      <xs:attribute name="group" type="xs:string" use="optional"/>
      <xs:attribute name="username" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="version">
    <xs:complexType mixed="true"/>
  </xs:element>

  <xs:element name="video">
    <xs:complexType mixed="true"/>
  </xs:element>

  <xs:element name="vm">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="filesystem"/>
        <!--xs:element ref="dynamips_conf" minOccurs="0" /-->
        <xs:element minOccurs="0" ref="mem"/>
        <xs:element minOccurs="0" ref="video"/>
        <xs:element minOccurs="0" ref="kernel"/>
        <xs:element minOccurs="0" ref="conf"/>
        <xs:element minOccurs="0" ref="shell"/>
        <xs:element minOccurs="0" ref="basedir"/>
        <xs:element minOccurs="0" ref="mng_if"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="console"/>
        <xs:element minOccurs="0" ref="on_boot"/>
        <!--xs:element ref="display_console" minOccurs="0" /-->
        <!--xs:element ref="xterm" minOccurs="0" /-->
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="if"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="route"/>
        <xs:element minOccurs="0" ref="forwarding"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="user"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="filetree"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="exec"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="type" type="xs:string" use="required"/>
      <xs:attribute name="subtype" type="xs:string" use="optional"/>
      <xs:attribute name="os" type="xs:string" use="optional"/>
      <xs:attribute name="arch" type="xs:string" use="optional"/>
      <xs:attribute name="vcpu" type="xs:unsignedByte" use="optional"/>
      <xs:attribute name="order" type="xs:string" use="optional"/>
      <xs:attribute name="exec_mode" type="xs:string" use="optional"/>
     </xs:complexType>
  </xs:element>

  <xs:element name="vm_defaults">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="filesystem"/>
        <xs:element minOccurs="0" ref="mem"/>
        <xs:element minOccurs="0" ref="kernel"/>
        <xs:element minOccurs="0" ref="shell"/>
        <xs:element minOccurs="0" ref="basedir"/>
        <xs:element minOccurs="0" ref="mng_if"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="console"/>
        <!-- DFC xs:element ref="display_console" minOccurs="0" /-->
        <!--xs:element ref="xterm" minOccurs="0" /-->
        <!-- DFC xs:element ref="route" minOccurs="0" maxOccurs="unbounded" /-->
        <xs:element minOccurs="0" ref="forwarding"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="user"/>
        <!-- DFC xs:element ref="filetree" minOccurs="0" maxOccurs="unbounded" /-->
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="exec_mode"/>
      </xs:sequence>
      
      <!-- DFC 26/8/2011: exec_mode attribute substituted by <exec_mode> tag -->
      <!--xs:attribute name="exec_mode" use="optional" default="net">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="net" />
            <xs:enumeration value="mconsole" />
            <xs:enumeration value="pst" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute-->
    </xs:complexType>
  </xs:element>

  <xs:element name="vm_mgmt">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="mgmt_net"/>
        <xs:element minOccurs="0" ref="host_mapping"/>
      </xs:sequence>
      <xs:attribute default="24" name="mask" type="xs:string" use="optional"/>
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="private"/>
            <xs:enumeration value="net"/>
            <xs:enumeration value="none"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute default="192.168.0.0" name="network" type="xs:string" use="optional"/>
      <xs:attribute default="0" name="offset" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="vnx">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="global"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="net"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="vm"/>
        <xs:element minOccurs="0" ref="host"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!--xs:element name="xterm">
    <xs:complexType mixed="true" />
  </xs:element-->

</xs:schema>

=== davidfdezc/vnx/vnx-folder/data/tutorial_lxc_ubuntu-sdn.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--

~~~~~~~~~~~~~~~~~~~~
VNX Sample scenarios
~~~~~~~~~~~~~~~~~~~~

Name:        tutorial_lxc_ubuntu-sdn
Description: As simple tutorial scenario made of 6 Ubuntu virtual machines (4 hosts: h1, h2, h3 and h4; 
             and 2 routers: r1 and r2) connected through three virtual networks based on Openvswitch. The host participates 
             in the scenario having a network interface in Net3.     
             Another VM, sdnctrl, run and SDN controller that controls the Openvswitchs of the scenario.

This file is part of the Virtual Networks over LinuX (VNX) Project distribution. 
(www: http://www.dit.upm.es/vnx - e-mail: vnx@dit.upm.es) 

Departamento de Ingenieria de Sistemas Telematicos (DIT)
Universidad Politecnica de Madrid
SPAIN

-->

<vnx xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="/usr/share/xml/vnx/vnx-2.00.xsd">
  <global>
    <version>2.0</version>
    <scenario_name>tutorial_lxc_ubuntu_sdn</scenario_name>
    <automac/>
    <vm_mgmt type="none" />
    <!--vm_mgmt type="private" network="10.250.0.0" mask="24" offset="200">
       <host_mapping />
    </vm_mgmt-->
    <vm_defaults>
        <console id="0" display="no"/>
        <console id="1" display="yes"/>
    </vm_defaults>

    <cmd-seq seq="ls12">ls1,ls2</cmd-seq>
    <cmd-seq seq="ls123">ls12,ls3</cmd-seq>
    <cmd-seq seq="ls1234">ls123,ls4</cmd-seq>

    <help>
        <seq_help seq='start-www'>Start apache2 web server</seq_help>
        <seq_help seq='stop-www'>Stop apache2 web server</seq_help>
    </help>
    
  </global>

  <net name="Net0"   mode="openvswitch" controller="tcp:10.1.4.2:6633" of_version="OpenFlow10" />
  <net name="Net1"   mode="openvswitch" controller="tcp:10.1.4.2:6633" of_version="OpenFlow10" />
  <net name="Net2"   mode="openvswitch" controller="tcp:10.1.4.2:6633" of_version="OpenFlow10" />
  <net name="Net3"   mode="openvswitch" controller="tcp:10.1.4.2:6633" of_version="OpenFlow10" />
  <net name="MgmtNet" mode="openvswitch" />

  <vm name="h1" type="lxc">
    <filesystem type="cow">/usr/share/vnx/filesystems/rootfs_lxc</filesystem>
    <if id="1" net="Net0">
      <ipv4>10.1.0.2/24</ipv4>
    </if>
    <route type="ipv4" gw="10.1.0.1">default</route>   
    <filetree seq="on_boot" root="/tmp/">conf/tutorial_lxc_ubuntu-sdn/hosts</filetree>
    <exec seq="on_boot" type="verbatim">cat /tmp/hosts >> /etc/hosts</exec>
  </vm>

  <vm name="h2" type="lxc">
    <filesystem type="cow">/usr/share/vnx/filesystems/rootfs_lxc</filesystem>
    <if id="1" net="Net0">
      <ipv4>10.1.0.3/24</ipv4>
    </if>
    <route type="ipv4" gw="10.1.0.1">default</route>
    <filetree seq="on_boot" root="/tmp/">conf/tutorial_lxc_ubuntu-sdn/hosts</filetree>
    <exec seq="on_boot" type="verbatim">cat /tmp/hosts >> /etc/hosts</exec>
  </vm>

  <vm name="r1" type="lxc">
    <filesystem type="cow">/usr/share/vnx/filesystems/rootfs_lxc</filesystem>
    <if id="1" net="Net0">
      <ipv4>10.1.0.1/24</ipv4>
    </if>
    <if id="2" net="Net1">
      <ipv4>10.1.1.1/24</ipv4>
    </if>
    <if id="3" net="Net3">
      <ipv4>10.1.3.1/24</ipv4>
    </if>
    <route type="ipv4" gw="10.1.1.2">10.1.2.0/24</route>
    <forwarding type="ip" />
    <filetree seq="on_boot" root="/tmp/">conf/tutorial_lxc_ubuntu-sdn/hosts</filetree>
    <exec seq="on_boot" type="verbatim">cat /tmp/hosts >> /etc/hosts</exec>
  </vm>

  <vm name="r2" type="lxc">
    <filesystem type="cow">/usr/share/vnx/filesystems/rootfs_lxc</filesystem>
    <if id="1" net="Net1" name="s1/0">
      <ipv4>10.1.1.2/24</ipv4>
    </if>
    <if id="2" net="Net2" name="e0/0">
      <ipv4>10.1.2.1/24</ipv4>
    </if>
    <route type="ipv4" gw="10.1.1.1">default</route>
    <forwarding type="ip" />
    <filetree seq="on_boot" root="/tmp/">conf/tutorial_lxc_ubuntu-sdn/hosts</filetree>
    <exec seq="on_boot" type="verbatim">cat /tmp/hosts >> /etc/hosts</exec>
  </vm>

  <vm name="h3" type="lxc">
   <filesystem type="cow">/usr/share/vnx/filesystems/rootfs_lxc</filesystem>
   <if id="1" net="Net2">
      <ipv4>10.1.2.2/24</ipv4>
    </if>
    <route type="ipv4" gw="10.1.2.1">default</route>
    <filetree seq="on_boot" root="/tmp/">conf/tutorial_lxc_ubuntu-sdn/hosts</filetree>
    <!-- Copy the files under conf/tutorial_ubuntu/h3 to vm /var/www directory -->
    <filetree seq="start-www" root="/var/www/">conf/tutorial_ubuntu/h3</filetree>
    <exec seq="on_boot" type="verbatim">cat /tmp/hosts >> /etc/hosts</exec>
    <!-- Start/stop apache www server -->
    <exec seq="start-www" type="verbatim" ostype="system">chmod 644 /var/www/*</exec>
    <exec seq="start-www" type="verbatim" ostype="system">service apache2 start</exec>
    <exec seq="stop-www" type="verbatim"  ostype="system">service apache2 stop</exec>    
  </vm>
  
  <vm name="h4" type="lxc">
    <filesystem type="cow">/usr/share/vnx/filesystems/rootfs_lxc</filesystem>
    <if id="1" net="Net2">
      <ipv4>10.1.2.3/24</ipv4>
    </if>
    <route type="ipv4" gw="10.1.2.1">default</route>    
    <filetree seq="on_boot" root="/tmp/">conf/tutorial_lxc_ubuntu-sdn/hosts</filetree>
    <!-- Copy the files under conf/tutorial_ubuntu/h4 to vm /var/www directory -->
    <filetree seq="start-www" root="/var/www/">conf/tutorial_ubuntu/h4</filetree>
    <exec seq="on_boot" type="verbatim">cat /tmp/hosts >> /etc/hosts</exec>
    <!-- Start/stop apache www server -->
    <exec seq="start-www" type="verbatim" ostype="system">chmod 644 /var/www/*</exec>
    <exec seq="start-www" type="verbatim" ostype="system">service apache2 start</exec>
    <exec seq="stop-www" type="verbatim"  ostype="system">service apache2 stop</exec>    
  </vm>

  <vm name="sdnctrl" type="lxc">
    <filesystem type="cow">/usr/share/vnx/filesystems/rootfs_sdn</filesystem>
    <if id="1" net="MgmtNet">
      <ipv4>10.1.4.2/24</ipv4>
    </if>
    <route type="ipv4" gw="10.1.2.1">default</route>    

    <filetree seq="on_boot" root="/tmp/">conf/tutorial_lxc_ubuntu-sdn/hosts</filetree>
    <filetree seq="on_boot" root="/root/floodlight/">conf/tutorial_lxc_ubuntu-sdn/sdnctrl/</filetree>

    <exec seq="on_boot" type="verbatim">cat /tmp/hosts >> /etc/hosts</exec>
    <exec seq="on_boot" type="verbatim">
       mkdir -p /etc/floodlight;
       ln -s /root/floodlight/floodlight.properties /etc/floodlight/;
    </exec>
    <exec seq="on_boot" type="verbatim">chmod +x /root/floodlight/start-floodlight</exec>
    <!--exec seq="on_boot,start_ctrl" type="verbatim">/root/floodlight/start-floodlight</exec-->
    <exec seq="on_boot,start_ctrl" type="verbatim">java -Dlogback.configurationFile=/root/floodlight/logback.xml -jar /root/floodlight/target/floodlight.jar -cf /etc/floodlight/floodlight.properties &amp;</exec>

    <exec seq="stop_ctrl" type="verbatim">pkill -f "java -Dlogback.configurationFile"</exec>

  </vm>
  
  <host>
    <hostif net="Net3">
       <ipv4>10.1.3.2/24</ipv4>
    </hostif>
    <hostif net="MgmtNet">
       <ipv4>10.1.4.1/24</ipv4>
    </hostif>
    <route type="ipv4" gw="10.1.3.1">10.1.0.0/16</route>
  </host>

</vnx>

=== davidfdezc/vnx/vnx-plugins/dummy/examples/example_dummy-plugin.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--

~~~~~~~~~~~~~~~~~~~~
VNX Sample scenarios
~~~~~~~~~~~~~~~~~~~~

Name:        example_dummy-plugin
Description: Example scenario to show the use of the dummy plugin. It is made of two 
             ubuntu vm: h1 and h2.   

This file is part of the Virtual Networks over LinuX (VNX) Project distribution. 
(www: http://www.dit.upm.es/vnx - e-mail: vnx@dit.upm.es) 

Departamento de Ingenieria de Sistemas Telematicos (DIT)
Universidad Politecnica de Madrid
SPAIN

-->

<vnx xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="/usr/share/xml/vnx/vnx-2.00.xsd">
  <global>
    <version>2.0</version>
    <scenario_name>example_ospf-plugin</scenario_name>
    <ssh_key>~/.ssh/id_dsa.pub</ssh_key>
    <automac offset="4"/>
    <!--vm_mgmt type="none" /-->
    <vm_mgmt type="private" network="10.250.0.0" mask="24" offset="16">
       <host_mapping />
    </vm_mgmt> 
    <vm_defaults>
	    <console id="0" display="no"/>
	    <console id="1" display="yes"/>
        <exec_mode type="uml">mconsole</exec_mode>
        <exec_mode type="libvirt" subtype="kvm">cdrom</exec_mode>
        <exec_mode type="libvirt" subtype="kvm" os="windows">cdrom</exec_mode>
        <exec_mode type="libvirt" subtype="kvm" os="olive">sdisk</exec_mode>
    </vm_defaults>
    <extension plugin="dummy" conf="example_dummy-plugin-conf.xml" />
    
    <help>
         <seq_help seq='start-www'>Start apache2 web server</seq_help>
         <seq_help seq='stop-www'>Stop apache2 web server</seq_help>     
    </help>
    
  </global>
    
  <net name="lan1" mode="virtual_bridge" />
  
  <!-- NODES -->

  <vm name="h1" type="libvirt" subtype="kvm" os="linux" exec_mode="sdisk">
    <filesystem type="cow">/usr/share/vnx/filesystems/rootfs_ubuntu</filesystem>
    <mem>256M</mem>
    <if id="1" net="lan1">
      <ipv4>10.0.1.2/24</ipv4>
      <ipv6>2001:db8:1::2/64</ipv6>
    </if>
    <route type="ipv4" gw="10.0.1.1">default</route>    
    <route type="ipv6" gw="2001:db8:1::1">default</route>       
  </vm>

  <vm name="h2" type="libvirt" subtype="kvm" os="linux" exec_mode="sdisk">
    <filesystem type="cow">/usr/share/vnx/filesystems/rootfs_ubuntu</filesystem>
    <mem>256M</mem>
    <if id="1" net="lan1">
      <ipv4>10.0.1.3/24</ipv4>
      <ipv6>2001:db8:1::3/64</ipv6>
    </if>
    <route type="ipv4" gw="10.0.2.1">default</route>    
    <route type="ipv6" gw="2001:db8:2::1">default</route>       
  </vm>
  

  <host>
    <hostif net="lan1">
       <ipv4>10.0.1.1/24</ipv4>
       <ipv6>2001:db8:1::1/64</ipv6>
    </hostif>
    <route type="ipv4" gw="10.0.1.1">10.0.0.0/16</route>    
    <route type="ipv6" gw="2001:db8:1::1">2001:db8::/32</route>    
  </host>
  
</vnx>
