=== davidfdezc/vnx/vnx-folder/data/vnx-1.92.dtd
<!-- VNX DTD version 1.92 -->
<!ELEMENT vnx (global,net*,vm*,host?)>
<!ELEMENT global (version,scenario_name,ssh_version?,ssh_key*,automac?,netconfig?,vm_mgmt?,
          tun_device?,vm_defaults?,extension*)>
<!ELEMENT vm_defaults (filesystem?,mem?,kernel?,shell?,basedir?,
          mng_if?,console*,xterm?,route*,forwarding?,user*,filetree*)>
<!ATTLIST vm_defaults exec_mode (net|mconsole|pst) "net">
<!ELEMENT extension EMPTY>
<!ATTLIST extension plugin CDATA #REQUIRED
	                conf CDATA #REQUIRED>
<!ELEMENT net (bw?)>
<!ATTLIST net name CDATA #REQUIRED
              mode (virtual_bridge|uml_switch) #REQUIRED
			  sock CDATA #IMPLIED
              type (lan|ppp) "lan"
              external CDATA #IMPLIED
              vlan CDATA #IMPLIED
              uml_switch_binary CDATA #IMPLIED
              hub (yes|no) "no"
              scope (shared|no-shared) "no-shared"
              capture_file CDATA #IMPLIED
              capture_expression CDATA #IMPLIED
              capture_dev CDATA #IMPLIED>
<!ELEMENT vm (filesystem?,mem?,kernel?,shell?,basedir?,mng_if?,console*,xterm?,if*,
              route*,forwarding?,user*,filetree*,exec*)>
<!ATTLIST vm name CDATA #REQUIRED
             type CDATA #REQUIRED
             subtype CDATA #REQUIRED
             os CDATA #REQUIRED
             order CDATA #IMPLIED
             exec_mode (net|mconsole|pst) "net">
<!ELEMENT host (hostif*,physicalif*,route*,forwarding?,exec*)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT scenario_name (#PCDATA)>
<!ELEMENT ssh_version (#PCDATA)>
<!ELEMENT ssh_key (#PCDATA)>
<!ELEMENT automac EMPTY>
<!ATTLIST automac offset CDATA "0">
<!ELEMENT netconfig EMPTY>
<!ATTLIST netconfig stp (on|off) "off"
                    promisc (on|off) "on">
<!ELEMENT vm_mgmt (mgmt_net?,host_mapping?)>
<!ATTLIST vm_mgmt type (private|net|none) #REQUIRED
			     network CDATA "192.168.0.0"
                 mask CDATA "24"
				 offset CDATA "0">
<!ELEMENT mgmt_net EMPTY>
<!ATTLIST mgmt_net sock CDATA #REQUIRED 
				hostip CDATA #REQUIRED
				autoconfigure CDATA #IMPLIED>
<!ELEMENT host_mapping EMPTY>
<!ELEMENT shell (#PCDATA)>
<!ELEMENT tun_device (#PCDATA)>
<!ELEMENT basedir (#PCDATA)>
<!ELEMENT bw (#PCDATA)>
<!ELEMENT filesystem (#PCDATA)>
<!ATTLIST filesystem type (direct|cow|hostfs) #REQUIRED>
<!ELEMENT mem (#PCDATA)>
<!ELEMENT kernel (#PCDATA)>
<!ATTLIST kernel initrd CDATA #IMPLIED
					devfs (mount|nomount) #IMPLIED
					root CDATA #IMPLIED
					modules CDATA #IMPLIED
					trace (on|off) "off">
<!ELEMENT mng_if (#PCDATA)>
<!ELEMENT console (#PCDATA)>
<!ATTLIST console id CDATA #REQUIRED>
<!ELEMENT if (mac?,ipv4*,ipv6*)>
<!ATTLIST if id CDATA #REQUIRED
             net CDATA #REQUIRED>
<!ELEMENT route (#PCDATA)>
<!ATTLIST route type (ipv4|ipv6) #REQUIRED
                gw CDATA #REQUIRED>
<!ELEMENT forwarding EMPTY>
<!ATTLIST forwarding type (ip|ipv4|ipv6) "ip">
<!ELEMENT user (group*,ssh_key*)>
<!ATTLIST user username CDATA #REQUIRED
			   group CDATA #IMPLIED>
<!ELEMENT group (#PCDATA)>
<!ELEMENT filetree (#PCDATA)>
<!ATTLIST filetree root CDATA #REQUIRED
                   seq CDATA #REQUIRED
                   user CDATA #IMPLIED>
<!ELEMENT exec (#PCDATA)>
<!ATTLIST exec type (verbatim|file) #REQUIRED
               seq CDATA #REQUIRED
	       mode (mconsole|net|pts|system|processn|processy) #IMPLIED
	       gui (yes|no) #IMPLIED
               user CDATA #IMPLIED>
<!ELEMENT hostif (ipv4*,ipv6*)>
<!ATTLIST hostif net CDATA #REQUIRED>
<!ELEMENT mac (#PCDATA)>
<!ELEMENT ipv4 (#PCDATA)>
<!ATTLIST ipv4 mask CDATA "255.255.255.0">
<!ELEMENT ipv6 (#PCDATA)>
<!ATTLIST ipv6 mask CDATA #IMPLIED>
<!ELEMENT physicalif EMPTY>
<!ATTLIST physicalif name CDATA #REQUIRED
                     type (ipv4|ipv6) "ipv4"
                     ip CDATA #REQUIRED
                     mask CDATA #IMPLIED
                     gw CDATA #IMPLIED>
<!ELEMENT xterm (#PCDATA)>

=== davidfdezc/vnx/vnx-folder/data/simple_freebsd-gui.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vnx SYSTEM "/usr/share/xml/vnx/vnx-1.92.dtd">

<!--

Simple scenario
Just one FreeBSD virtual machine. Use this specification for testing

-->

<vnx>
  <global>
    <version>1.92</version>
    <scenario_name>simple_freebsd</scenario_name>
    <automac offset="5"/>
    <vm_mgmt type="none" />
  </global>
    
  <net name="Net0" mode="virtual_bridge" />
      
  <!-- NODES -->
  <vm name="freebsd" type="libvirt" subtype="kvm" os="linux">
    <filesystem type="cow">/usr/share/vnx/filesystems/root_fs_freebsd-gui</filesystem>
    <mem>256M</mem>
    <if id="1" net="Net0">
      <ipv4>10.0.0.5</ipv4>
    </if>
    <filetree seq="vnxtxt" root="/tmp">conf/txtfile</filetree>
    <exec seq="vnxtxt" type="verbatim" mode="processn">gedit /tmp/vnx.txt</exec>
    <exec seq="vnxtxt2" type="verbatim" mode="system">'sleep 5; wmctrl -r vnx.txt -b add,maximized_vert,maximized_horz'</exec>
    <exec seq="showlog" type="verbatim" mode="system">tail -f /var/log/vnxdaemon.log</exec>
  </vm>

</vnx>

=== davidfdezc/vnx/vnx-folder/data/simple_ubuntu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vnx SYSTEM "/usr/share/xml/vnx/vnx-1.92.dtd">

<!--

Simple scenario
Just one Ubuntu virtual machine. Use this specification for testing

-->

<vnx>
  <global>
    <version>1.92</version>
    <scenario_name>simple_ubuntu</scenario_name>
    <automac offset="2"/>
    <vm_mgmt type="none" />
  </global>
    
  <net name="Net0" mode="virtual_bridge" />
  
  <!-- NODES -->
  <vm name="ubuntu" type="libvirt" subtype="kvm" os="linux">
    <filesystem type="cow">/usr/share/vnx/filesystems/root_fs_ubuntu</filesystem>
    <mem>256M</mem>
    <if id="1" net="Net0">
      <ipv4>10.0.0.3</ipv4>
    </if>
    <filetree seq="copyfile" root="/tmp">conf/txtfile</filetree>
    <filetree seq="start-www" root="/var/www">conf/txtfile</filetree>
    <exec seq="movefile" type="verbatim" mode="system">mv /tmp/vnx.txt /root/</exec>
    <exec seq="start-www" type="verbatim" mode="system">/etc/init.d/apache2 start</exec>
    <exec seq="stop-www" type="verbatim" mode="system">/etc/init.d/apache2 stop</exec>
  </vm>

</vnx>

=== davidfdezc/vnx/vnx-folder/data/simple_olive.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vnx SYSTEM "/usr/share/xml/vnx/vnx-1.92.dtd">

<!--

Simple scenario
Just one Juniper olive virtual machine. Use this specification for testing

-->

<vnx>
  <global>
    <version>1.92</version>
    <scenario_name>simple_juniper</scenario_name>
    <automac offset="11"/>
    <vm_mgmt type="none" />
  </global>
    
  <net name="Net0" mode="virtual_bridge" />
      
  <!-- NODES -->
  <vm name="juniper" type="libvirt" subtype="kvm" os="olive">
    <filesystem type="cow">/usr/share/vnx/filesystems/root_fs_juniper</filesystem>
    <mem>256M</mem>
    <if id="1" net="Net0">
      <ipv4>10.0.0.11/24</ipv4>
    </if>
  </vm>

  <host>
    <hostif net="Net0">
       <ipv4>10.0.0.1/24</ipv4>
    </hostif>
  </host>
  
</vnx>

=== davidfdezc/vnx/vnx-folder/data/simple_xp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vnx SYSTEM "/usr/share/xml/vnx/vnx-1.92.dtd">

<!--

Simple simulation
Just one Windows XP virtual machine. Use this specification for testing

-->

<vnx>
  <global>
    <version>1.92</version>
    <simulation_name>simple</simulation_name>
    <automac/>
    <vm_mgmt type="none" />
    <vm_defaults exec_mode="mconsole">
    </vm_defaults>
  </global>
    
  <!-- NODES -->
  <vm name="host1" type="libvirt" subtype="kvm" os="windows">
    <filesystem type="cow">/usr/share/vnx/filesystems/root_fs_winxp</filesystem>
    <mem>256M</mem>
  </vm>

</vnx>

=== davidfdezc/vnx/vnx-folder/data/simple_ubuntu-gui.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vnx SYSTEM "/usr/share/xml/vnx/vnx-1.92.dtd">

<!--

Simple scenario
Just one Ubuntu virtual machine. Use this specification for testing

-->

<vnx>
  <global>
    <version>1.92</version>
    <scenario_name>simple_ubuntu</scenario_name>
    <automac offset="2"/>
    <vm_mgmt type="none" />
  </global>
    
  <net name="Net0" mode="virtual_bridge" />
  
  <!-- NODES -->
  <vm name="ubuntu" type="libvirt" subtype="kvm" os="linux">
    <filesystem type="cow">/usr/share/vnx/filesystems/root_fs_ubuntu-gui</filesystem>
    <mem>256M</mem>
    <if id="1" net="Net0">
      <ipv4>10.0.0.3</ipv4>
    </if>
    <filetree seq="vnxtxt" root="/tmp">conf/txtfile</filetree>
    <exec seq="vnxtxt" type="verbatim" mode="system">gedit /tmp/vnx.txt</exec>
    <exec seq="vnxtxt2" type="verbatim" mode="system">'sleep 5; wmctrl -r vnx.txt -b add,maximized_vert,maximized_horz'</exec>
    <exec seq="vnxtxtoff" type="verbatim" mode="system">pkill gedit</exec>
    <exec seq="calc" type="verbatim" mode="system">gcalctool</exec>    
    <exec seq="calcoff" type="verbatim" mode="system">pkill gcalctool</exec>
    <exec seq="ping" type="verbatim" mode="system">'ping 10.0.0.1'</exec>
    <exec seq="showlog" type="verbatim" mode="system">tail -f /var/log/vnxdaemon.log</exec>
  </vm>

</vnx>

=== davidfdezc/vnx/vnx-folder/data/simple_freebsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vnx SYSTEM "/usr/share/xml/vnx/vnx-1.92.dtd">

<!--

Simple simulation
Just one FreeBSD virtual machine. Use this specification for testing

-->

<vnx>
  <global>
    <version>1.92</version>
    <simulation_name>simple_freebsd</simulation_name>
    <automac offset="5"/>
    <vm_mgmt type="none" />
  </global>
    
  <net name="Net0" mode="virtual_bridge" />
      
  <!-- NODES -->
  <vm name="freebsd" type="libvirt" subtype="kvm" os="linux">
    <filesystem type="cow">/usr/share/vnx/filesystems/root_fs_freebsd</filesystem>
    <mem>256M</mem>
    <if id="1" net="Net0">
      <ipv4>10.0.0.5</ipv4>
    </if>
  </vm>

</vnx>
