=== davidfdezc/vnx/vnx-folder/data/vnx-2.00.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--

VNX Virtual Scenarios Definition Language v2.00

Virtual Networks over LinuX (VNX) Project 
www:    http://www.dit.upm.es/vnx 
e-mail: vnx@dit.upm.es 

-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <xs:element name="automac">
    <xs:complexType>
      <xs:attribute default="0" name="offset" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="basedir">
    <xs:complexType mixed="true"/>
  </xs:element>

  <xs:element name="bw">
    <xs:complexType mixed="true"/>
  </xs:element>

  <xs:element name="cmd-seq">
    <xs:complexType mixed="true">
      <xs:attribute name="seq" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="conf">
    <xs:complexType mixed="true"/>
  </xs:element>

  <xs:element name="console">
    <xs:complexType mixed="true">
      <xs:attribute name="id" type="xs:string" use="required"/>
      <xs:attribute name="display" type="xs:string" use="optional"/>
      <xs:attribute name="port" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="dynamips_ext">
    <xs:complexType mixed="true"/>
  </xs:element>

  <xs:element name="exec">
    <xs:complexType mixed="true">
      <xs:attribute name="user" type="xs:string" use="optional"/>
      <xs:attribute name="seq" type="xs:string" use="required"/>
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="verbatim"/>
            <xs:enumeration value="file"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="ostype" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="system"/>
            <xs:enumeration value="exec"/>
            <xs:enumeration value="xsystem"/>
            <xs:enumeration value="xexec"/>
            <xs:enumeration value="cmd"/>
            <xs:enumeration value="show"/>
            <xs:enumeration value="set"/>
            <xs:enumeration value="load"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="seq_help">
    <xs:complexType mixed="true">
      <xs:attribute name="seq" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="exec_mode">
    <xs:complexType mixed="true">
      <xs:attribute name="type" type="xs:string" use="required"/>
      <xs:attribute name="subtype" type="xs:string" use="optional"/>
      <xs:attribute name="os" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="extension">
    <xs:complexType>
      <xs:attribute name="conf" type="xs:string" use="required"/>
      <xs:attribute name="plugin" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="filesystem">
    <xs:complexType mixed="true">
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="direct"/>
            <xs:enumeration value="cow"/>
            <xs:enumeration value="hostfs"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="filetree">
    <xs:complexType mixed="true">
      <xs:attribute name="seq" type="xs:string" use="required"/>
      <xs:attribute name="root" type="xs:string" use="required"/>
      <xs:attribute name="user" type="xs:string" use="optional"/>
      <xs:attribute name="group" type="xs:string" use="optional"/>
      <xs:attribute name="perms" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="forwarding">
    <xs:complexType>
      <xs:attribute default="ip" name="type" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="ip"/>
            <xs:enumeration value="ipv4"/>
            <xs:enumeration value="ipv6"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="global">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="version"/>
        <xs:element ref="scenario_name"/>
        <xs:element minOccurs="0" ref="ssh_version"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="ssh_key"/>
        <xs:element minOccurs="0" ref="automac"/>
        <xs:element minOccurs="0" ref="netconfig"/>
        <xs:element ref="vm_mgmt"/>
        <xs:element minOccurs="0" ref="tun_device"/>
        <xs:element minOccurs="0" ref="vm_defaults"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="cmd-seq"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="extension"/>
        <xs:element maxOccurs="1" minOccurs="0" ref="dynamips_ext"/>
        <xs:element maxOccurs="1" minOccurs="0" ref="olive_ext"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="help"/>        
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="group">
    <xs:complexType mixed="true"/>
  </xs:element>

  <xs:element name="help">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="seq_help"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="host">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="hostif"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="physicalif"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="route"/>
        <xs:element minOccurs="0" ref="forwarding"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="exec"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="host_mapping" type="xs:string"/>

  <xs:element name="hostif">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="vlan"/>	
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="ipv4"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="ipv6"/>
      </xs:sequence>
      <xs:attribute name="net" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="if">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="vlan"/>	
        <xs:element minOccurs="0" ref="mac"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="ipv4"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="ipv6"/>

      </xs:sequence>
      <xs:attribute name="net" type="xs:string" use="required"/>
      <xs:attribute name="id" type="xs:string" use="required"/>

      <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="ipv4">
    <xs:complexType mixed="true">
      <xs:attribute default="255.255.255.0" name="mask" type="xs:string" use="optional"/>
      <xs:attribute default="primary" name="type" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="ipv6">
    <xs:complexType mixed="true">
      <xs:attribute name="mask" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="vlan">
    <xs:complexType>
     <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="tag"/>	
     </xs:sequence>
    <xs:attribute name="trunk" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>

 <xs:element name="tag">
    <xs:complexType>
      <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="kernel">
    <xs:complexType mixed="true">
      <xs:attribute name="root" type="xs:string" use="optional"/>
      <xs:attribute name="devfs" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="mount"/>
            <xs:enumeration value="nomount"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="modules" type="xs:string" use="optional"/>
      <xs:attribute name="initrd" type="xs:string" use="optional"/>
      <xs:attribute default="off" name="trace" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="on"/>
            <xs:enumeration value="off"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="mac">
    <xs:complexType mixed="true"/>
  </xs:element>

  <xs:element name="mem">
    <xs:complexType mixed="true"/>
  </xs:element>

  <xs:element name="mgmt_net">
    <xs:complexType>
      <xs:attribute name="net" type="xs:string" use="optional"/>
      <xs:attribute name="managed" type="xs:string" use="optional"/>
      <xs:attribute name="config" type="xs:string" use="optional"/>
      <!--xs:attribute name="sock" type="xs:string" use="required"/>
      <xs:attribute name="hostip" type="xs:string" use="required"/>
      <xs:attribute name="autoconfigure" type="xs:string" use="optional"/-->
    </xs:complexType>
  </xs:element>

  <xs:element name="mng_if">
    <xs:complexType mixed="true"/>
  </xs:element>

<xs:element name="connection">
    <xs:complexType>
       <xs:sequence>
          <xs:element minOccurs="0" ref="vlan"/>  
   </xs:sequence>
      <xs:attribute name="net" type="xs:string" use="required"/>
      <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="net">
    <xs:complexType>
      <xs:sequence>
        <xs:element  minOccurs="0" ref="bw"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="connection"/>
      </xs:sequence>
      <xs:attribute name="capture_dev" type="xs:string" use="optional"/>
      <xs:attribute name="sock" type="xs:string" use="optional"/>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="uml_switch_binary" type="xs:string" use="optional"/>
      <xs:attribute name="vlan" type="xs:string" use="optional"/>
      <xs:attribute name="capture_file" type="xs:string" use="optional"/>
      <xs:attribute name="controller" type="xs:string" use="optional"/>
      <xs:attribute name="of_version" type="xs:string" use="optional"/>
      <xs:attribute name="mode" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="virtual_bridge"/>
            <xs:enumeration value="uml_switch"/>
            <xs:enumeration value="openvswitch"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute default="yes" name="managed" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="yes"/>
            <xs:enumeration value="no"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="external" type="xs:string" use="optional"/>
      <xs:attribute default="no" name="hub" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="yes"/>
            <xs:enumeration value="no"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute default="lan" name="type" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="lan"/>
            <xs:enumeration value="ppp"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="capture_expression" type="xs:string" use="optional"/>
      <xs:attribute default="no-shared" name="scope" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="shared"/>
            <xs:enumeration value="no-shared"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="netconfig">
    <xs:complexType>
      <xs:attribute default="on" name="promisc" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="on"/>
            <xs:enumeration value="off"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute default="off" name="stp" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="on"/>
            <xs:enumeration value="off"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="olive_ext">
    <xs:complexType mixed="true"/>
  </xs:element>

  <xs:element name="on_boot">
    <xs:complexType mixed="true"/>
  </xs:element>

  <xs:element name="physicalif">
    <xs:complexType>
      <xs:attribute name="mask" type="xs:string" use="optional"/>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute default="ipv4" name="type" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="ipv4"/>
            <xs:enumeration value="ipv6"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="gw" type="xs:string" use="optional"/>
      <xs:attribute name="ip" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="route">
    <xs:complexType mixed="true">
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="ipv4"/>
            <xs:enumeration value="ipv6"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="gw" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="shell">
    <xs:complexType mixed="true"/>
  </xs:element>

  <xs:element name="scenario_name">
    <xs:complexType mixed="true"/>
  </xs:element>

  <xs:element name="ssh_key">
    <xs:complexType mixed="true"/>
  </xs:element>

  <xs:element name="ssh_version">
    <xs:complexType mixed="true"/>
  </xs:element>

  <xs:element name="tun_device">
    <xs:complexType mixed="true"/>
  </xs:element>

  <xs:element name="user">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="group"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="ssh_key"/>
      </xs:sequence>
      <xs:attribute name="group" type="xs:string" use="optional"/>
      <xs:attribute name="username" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="version">
    <xs:complexType mixed="true"/>
  </xs:element>

  <xs:element name="video">
    <xs:complexType mixed="true"/>
  </xs:element>

  <xs:element name="vm">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="filesystem"/>
        <!--xs:element ref="dynamips_conf" minOccurs="0" /-->
        <xs:element minOccurs="0" ref="mem"/>
        <xs:element minOccurs="0" ref="video"/>
        <xs:element minOccurs="0" ref="kernel"/>
        <xs:element minOccurs="0" ref="conf"/>
        <xs:element minOccurs="0" ref="shell"/>
        <xs:element minOccurs="0" ref="basedir"/>
        <xs:element minOccurs="0" ref="mng_if"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="console"/>
        <xs:element minOccurs="0" ref="on_boot"/>
        <!--xs:element ref="display_console" minOccurs="0" /-->
        <!--xs:element ref="xterm" minOccurs="0" /-->
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="if"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="route"/>
        <xs:element minOccurs="0" ref="forwarding"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="user"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="filetree"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="exec"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="type" type="xs:string" use="required"/>
      <xs:attribute name="subtype" type="xs:string" use="optional"/>
      <xs:attribute name="os" type="xs:string" use="optional"/>
      <xs:attribute name="arch" type="xs:string" use="optional"/>
      <xs:attribute name="vcpu" type="xs:unsignedByte" use="optional"/>
      <xs:attribute name="order" type="xs:string" use="optional"/>
      <xs:attribute name="exec_mode" type="xs:string" use="optional"/>
     </xs:complexType>
  </xs:element>

  <xs:element name="vm_defaults">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="filesystem"/>
        <xs:element minOccurs="0" ref="mem"/>
        <xs:element minOccurs="0" ref="kernel"/>
        <xs:element minOccurs="0" ref="shell"/>
        <xs:element minOccurs="0" ref="basedir"/>
        <xs:element minOccurs="0" ref="mng_if"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="console"/>
        <!-- DFC xs:element ref="display_console" minOccurs="0" /-->
        <!--xs:element ref="xterm" minOccurs="0" /-->
        <!-- DFC xs:element ref="route" minOccurs="0" maxOccurs="unbounded" /-->
        <xs:element minOccurs="0" ref="forwarding"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="user"/>
        <!-- DFC xs:element ref="filetree" minOccurs="0" maxOccurs="unbounded" /-->
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="exec_mode"/>
      </xs:sequence>
      
      <!-- DFC 26/8/2011: exec_mode attribute substituted by <exec_mode> tag -->
      <!--xs:attribute name="exec_mode" use="optional" default="net">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="net" />
            <xs:enumeration value="mconsole" />
            <xs:enumeration value="pst" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute-->
    </xs:complexType>
  </xs:element>

  <xs:element name="vm_mgmt">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="mgmt_net"/>
        <xs:element minOccurs="0" ref="host_mapping"/>
      </xs:sequence>
      <xs:attribute default="24" name="mask" type="xs:string" use="optional"/>
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="private"/>
            <xs:enumeration value="net"/>
            <xs:enumeration value="none"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute default="192.168.0.0" name="network" type="xs:string" use="optional"/>
      <xs:attribute default="0" name="offset" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="vnx">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="global"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="net"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="vm"/>
        <xs:element minOccurs="0" ref="host"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!--xs:element name="xterm">
    <xs:complexType mixed="true" />
  </xs:element-->

</xs:schema>

=== davidfdezc/vnx/vnx-folder/data/simple_android3.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--

~~~~~~~~~~~~~~~~~~~~
VNX Sample scenarios
~~~~~~~~~~~~~~~~~~~~

Name:        simple_android_v3
Description: Just one Android X86 virtual machine with:
                + one interface connected to Net0 with address 10.1.0.26. The host has an interface 
                  in Net0 with address 10.1.0.1
                + another interface connected to 'virbr0' libvirt bridge to provide Internet connection.
             This simple scenario is supposed to be used for testing the different 
             types of virtual machines supported by VNX. You can start several simple_*.xml
             scenarios and test the connectivity among virtual machines and the host, as all
             scenarios share the same "Net0" network.  

This file is part of the Virtual Networks over LinuX (VNX) Project distribution. 
(www: http://www.dit.upm.es/vnx - e-mail: vnx@dit.upm.es) 

Departamento de Ingenieria de Sistemas Telematicos (DIT)
Universidad Politecnica de Madrid
SPAIN

-->

<vnx xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="/usr/share/xml/vnx/vnx-2.00.xsd">
  <global>
    <version>2.0</version>
    <scenario_name>simple_android</scenario_name>
    <automac offset="26"/>
    <vm_mgmt type="none" />
    <vm_defaults>
        <console id="0" display="yes"/>
        <console id="1" display="yes"/>
    </vm_defaults>
  </global>
    
  <net name="Net0" mode="virtual_bridge" />
  <net name="Net1" mode="virtual_bridge" />
  <net name="virbr0" mode="virtual_bridge" managed="no"/>
  
  <vm name="android" type="libvirt" subtype="kvm" os="android">
    <filesystem type="cow">/usr/share/vnx/filesystems/rootfs_android</filesystem>
    <mem>1G</mem>
    <video>vmvga</video>
    <if id="1" net="virbr0">
      <ipv4>dhcp</ipv4>
    </if>
    <if id="2" net="Net0">
      <ipv4>10.1.0.26/24</ipv4>
    </if>
  </vm>

  <host>
    <hostif net="Net0">
       <ipv4>10.1.0.1/24</ipv4>
    </hostif>
  </host>
  
</vnx>

=== davidfdezc/vnx/vnx-folder/data/simple_uml.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--

~~~~~~~~~~~~~~~~~~~~
VNX Sample scenarios
~~~~~~~~~~~~~~~~~~~~

Name:        simple_uml
Description: Just one Debian UML virtual machine with GUI connected to a Network named Net0 with address 10.0.0.2. 
             The host has an interface in Net0 with address 10.0.0.1  
             This simple scenario is supposed to be used for testing the different 
             types of virtual machines supported by VNX. You can start several simple_*.xml
             scenarios and test the connectivity among virtual machines and the host, as all
             scenarios share the same "Net0" network.  

This file is part of the Virtual Networks over LinuX (VNX) Project distribution. 
(www: http://www.dit.upm.es/vnx - e-mail: vnx@dit.upm.es) 

Departamento de Ingenieria de Sistemas Telematicos (DIT)
Universidad Politecnica de Madrid
SPAIN

-->

<vnx xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="/usr/share/xml/vnx/vnx-2.00.xsd">
  <global>
    <version>2.0</version>
    <scenario_name>simple_uml</scenario_name>
    <automac offset="2"/>
    <!--vm_mgmt type="none" /-->
    <vm_mgmt type="private" network="10.250.0.0" mask="24" offset="8">
       <host_mapping />
    </vm_mgmt> 
    <vm_defaults exec_mode="mconsole">
    </vm_defaults>
  </global>

  <net name="Net0" mode="virtual_bridge" />

  <!-- NODES -->
  <vm name="uml" type="uml" subtype="" os="">
    <filesystem type="cow">/usr/share/vnx/filesystems/rootfs_uml</filesystem>
    <mem>64M</mem>
    <kernel>/usr/share/vnx/kernels/linux</kernel>
    <console id="0" display="yes">xterm</console>
    <if id="1" net="Net0">
      <ipv4>10.0.0.2/24</ipv4>
    </if>
    <filetree seq="copyfile" root="/tmp">conf/txtfile</filetree>
    <filetree seq="start-www" root="/var/www">conf/txtfile</filetree>
    <exec seq="movefile" type="verbatim">mv /tmp/vnx.txt /root/</exec>
    <!--exec seq="start-www" type="verbatim">chmod 644 /var/www/*</exec-->
    <exec seq="start-www" type="verbatim">/etc/init.d/apache2 start</exec>
    <exec seq="stop-www" type="verbatim">/etc/init.d/apache2 stop</exec>
  </vm>

  <host>
    <hostif net="Net0">
       <ipv4>10.0.0.1/24</ipv4>
    </hostif>
  </host>
  
</vnx>

=== davidfdezc/vnx/vnx-folder/data/tutorial_ubuntu-dynamips.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
VNUML Root Scenario (1)
See the tutorial/index.html document for details
-->

<vnx xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="/usr/share/xml/vnx/vnx-2.00.xsd">
  <global>
    <version>2.0</version>
    <scenario_name>tutorial_ubuntu-dynamips</scenario_name>
    <automac/>
    <vm_mgmt type="none"/>
    <!--vm_mgmt type="private" network="10.250.0.0" mask="24">
       <host_mapping />
    </vm_mgmt--> 
    <vm_defaults>
    	<console id="0" display="no"/>
	    <console id="1" display="yes"/>
    </vm_defaults>
    <dynamips_ext>tutorial_ubuntu-dynamips-dn.xml</dynamips_ext>
  </global>

  <net name="Net0" mode="virtual_bridge" />
  <net name="Net1" mode="virtual_bridge" />
  <!--net name="Net1" type='ppp' mode="virtual_bridge" /-->
  <net name="Net2" mode="virtual_bridge" />
  <net name="Net3" mode="virtual_bridge" />

  <vm name="h1" type="libvirt" subtype="kvm" os="linux">
    <filesystem type="cow">/usr/share/vnx/filesystems/rootfs_ubuntu-gui</filesystem>
    <mem>384M</mem>
    <console id="0" display="yes"/>
    <console id="1" display="no"/>
    <if id="1" net="Net0">
      <ipv4>10.0.0.2/24</ipv4>
    </if>
    <route type="ipv4" gw="10.0.0.1">default</route>
    
    <filetree seq="vnxtxt" root="/tmp/" perms="644">conf/txtfile</filetree>

    <!-- Start xeyes application -->
    <exec seq="xeyes"     type="verbatim" ostype="xexec">xeyes</exec>

    <!-- Start xeyes application and wait until it is closed -->
    <exec seq="xeyes2"    type="verbatim" ostype="xsystem">xeyes</exec>

    <!-- Start gedit, maximize the window and show a text file -->
    <exec seq="vnxtxt"    type="verbatim" ostype="xexec">gedit /tmp/vnx.txt</exec>
    <exec seq="vnxtxt"    type="verbatim" ostype="xexec">sleep 3; wmctrl -r vnx.txt -b add,maximized_vert,maximized_horz</exec>
    <exec seq="vnxtxtoff" type="verbatim" ostype="system">pkill gedit; rm /tmp/vnx.*</exec>

    <!-- Start firefox and connect to h3 web server -->
    <exec seq="www-h3"    type="verbatim" ostype="xexec">firefox http://10.0.2.2</exec>
    <exec seq="www-h3-off" type="verbatim" ostype="system">pkill firefox</exec>

    <!-- Start calculator  -->
    <exec seq="calc"      type="verbatim" ostype="xexec">gcalctool</exec>
    <exec seq="calcoff"   type="verbatim" ostype="system">pkill gcalctool</exec>
   
  </vm>
  
  <vm name="h2" type="libvirt" subtype="kvm" os="linux">
    <filesystem type="cow">/usr/share/vnx/filesystems/rootfs_ubuntu</filesystem>
    <mem>128M</mem>
    <if id="1" net="Net0">
      <ipv4>10.0.0.3/24</ipv4>
    </if>
    <route type="ipv4" gw="10.0.0.3">default</route>
  </vm>

  <vm name="r1" type="dynamips" subtype="3600" os="">
    <filesystem type="cow">/usr/share/vnx/filesystems/c3640</filesystem>
    <mem>96M</mem>
    <if id="1" net="Net0" name="e0/0">
      <ipv4>10.0.0.1/24</ipv4>
    </if>
    <!--if id="2" net="Net1" name="s1/0"-->
    <if id="2" net="Net1" name="e0/2">
      <ipv4>10.0.1.1/24</ipv4>
    </if>
    <if id="3" net="Net3" name="e0/1">
      <ipv4>10.0.3.1/24</ipv4>
    </if>
    <route type="ipv4" gw="10.0.1.2">10.0.2.0/24</route>
    <exec seq="brief" type="verbatim"    ostype="show">show ip interface brief</exec>
    <exec seq="iproutes" type="verbatim" ostype="show">show ip route</exec>
    <exec seq="showcfg"  type="verbatim" ostype="show">show running-config</exec>    
  </vm>

  <vm name="r2" type="dynamips" subtype="3600" os="">
    <filesystem type="cow">/usr/share/vnx/filesystems/c3640</filesystem>
    <mem>96M</mem>
    <!--if id="1" net="Net1" name="s1/0"-->
    <if id="1" net="Net1" name="e0/1">
      <ipv4>10.0.1.2/24</ipv4>
    </if>
    <if id="2" net="Net2" name="e0/0">
      <ipv4>10.0.2.1/24</ipv4>
    </if>
    <route type="ipv4" gw="10.0.1.1">default</route>
    <exec seq="brief" type="verbatim"    ostype="show">show ip interface brief</exec>
    <exec seq="iproutes" type="verbatim" ostype="show">show ip route</exec>
    <exec seq="showcfg"  type="verbatim" ostype="show">show running-config</exec>    
  </vm>

  <vm name="h3" type="libvirt" subtype="kvm" os="linux">
    <filesystem type="cow">/usr/share/vnx/filesystems/rootfs_ubuntu</filesystem>
   <mem>128M</mem>
   <if id="1" net="Net2">
      <ipv4>10.0.2.2/24</ipv4>
    </if>
    <route type="ipv4" gw="10.0.2.1">default</route>
    <!-- Copy the files under conf/tutorial_ubuntu/h3 to vm /var/www directory -->
    <filetree seq="start-www" root="/var/www/">conf/tutorial_ubuntu/h3</filetree>
    <!-- Start/stop apache www server -->
    <exec seq="start-www" type="verbatim" ostype="system">chmod 644 /var/www/*</exec>
    <exec seq="start-www" type="verbatim" ostype="system">service apache2 start</exec>
    <exec seq="stop-www" type="verbatim"  ostype="system">service apache2 stop</exec>    
  </vm>
  
  <vm name="h4" type="libvirt" subtype="kvm" os="linux">
    <filesystem type="cow">/usr/share/vnx/filesystems/rootfs_ubuntu</filesystem>
    <mem>128M</mem>
    <if id="1" net="Net2">
      <ipv4>10.0.2.3/24</ipv4>
    </if>
    <route type="ipv4" gw="10.0.2.1">default</route> 
    <!-- Copy the files under conf/tutorial_ubuntu/h4 to vm /var/www directory -->
    <filetree seq="start-www" root="/var/www/">conf/tutorial_ubuntu/h4</filetree>
    <!-- Start/stop apache www server -->
    <exec seq="start-www" type="verbatim" ostype="system">chmod 644 /var/www/*</exec>
    <exec seq="start-www" type="verbatim" ostype="system">service apache2 start</exec>
    <exec seq="stop-www" type="verbatim"  ostype="system">service apache2 stop</exec>           
  </vm>
  
  <host>
    <hostif net="Net3">
       <ipv4>10.0.3.2/24</ipv4>
    </hostif>
    <route type="ipv4" gw="10.0.3.1">10.0.0.0/16</route>
  </host>

</vnx>
