=== davidfdezc/vnx/vnx-plugins/dhcp/dhcp.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!--

VNX DHCP Plugin Definition Language v1.0

Virtual Networks over LinuX (VNX) Project 
www:    http://www.dit.upm.es/vnx 
e-mail: vnx@dit.upm.es 

-->

 <xs:element name='dhcp_conf'>
  <xs:complexType>
   <xs:sequence>
    <xs:element ref='vm' maxOccurs='unbounded'/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>

 <xs:element name='vm'>
  <xs:complexType>
   <xs:sequence>
    <xs:element ref='server' minOccurs='0' maxOccurs='1'/>
    <xs:element ref='relay' minOccurs='0' maxOccurs='1'/>
    <xs:element ref='client' minOccurs='0' maxOccurs='1'/>
   </xs:sequence>
   <xs:attribute name='name' type='xs:string' use='required'/>
   <xs:attribute name='type' type='xs:string' use='required'/>
  </xs:complexType>
 </xs:element>

 <xs:element name='server'>
  <xs:complexType>
   <xs:sequence>
    <xs:element ref='subnet' maxOccurs='unbounded'/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>

 <xs:element name='subnet'>
  <xs:complexType>
   <xs:sequence>
    <xs:element ref='ip' />
    <xs:element ref='range' minOccurs='0' maxOccurs='unbounded'/>
    <xs:element ref='router' minOccurs='0' maxOccurs='unbounded'/>
    <xs:element ref='dns' minOccurs='0' maxOccurs='unbounded'/>
    <xs:element ref='domain' minOccurs='0' maxOccurs='1'/>
    <xs:element ref='host' minOccurs='0' maxOccurs='unbounded'/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>

 <xs:element name='ip'>
  <xs:complexType mixed='true'>
   <xs:attribute name='mask' type='xs:string' use='required'/>
  </xs:complexType>
 </xs:element>

 <xs:element name='range'>
  <xs:complexType>
   <xs:sequence>
    <xs:element ref='first'/>
    <xs:element ref='last'/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>

 <xs:element name='first'>
  <xs:complexType mixed='true'>
  </xs:complexType>
 </xs:element>

 <xs:element name='last'>
  <xs:complexType mixed='true'>
  </xs:complexType>
 </xs:element>

 <xs:element name='router'>
  <xs:complexType mixed='true'>
  </xs:complexType>
 </xs:element>

 <xs:element name='dns'>
  <xs:complexType mixed='true'>
  </xs:complexType>
 </xs:element>

 <xs:element name='domain'>
  <xs:complexType mixed='true'>
  </xs:complexType>
 </xs:element>

 <xs:element name='host'>
  <xs:complexType mixed='true'>
   <xs:attribute name='name' type='xs:string' use='required'/>
   <xs:attribute name='mac' type='xs:string' use='required'/>
   <xs:attribute name='ip' type='xs:string' use='required'/>
  </xs:complexType>
 </xs:element>

 <xs:element name='relay'>
  <xs:complexType>
   <xs:sequence>
    <xs:element ref='toserver' maxOccurs='unbounded'/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>

 <xs:element name='toserver'>
  <xs:complexType mixed='true'>
  </xs:complexType>
 </xs:element>

 <xs:element name='client'>
  <xs:complexType>
   <xs:sequence>
    <xs:element ref='if' maxOccurs='unbounded'/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>

 <xs:element name='if'>
  <xs:complexType mixed='true'>
  </xs:complexType>
 </xs:element>
</xs:schema>

=== davidfdezc/vnx/vnx-plugins/dhcp/examples/example_dhcp-plugin-lxc-conf.xml
<dhcp_conf xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="/usr/share/xml/vnx/dhcp.xsd">

  <vm name="r1" type="dhcp3-isc">
    <server>
      <subnet>
        <network>10.0.1.0/24</network>
        <range>
          <first>10.0.1.10</first>
          <last>10.0.1.20</last>
        </range>
        <router>10.0.1.1</router>
        <dns>10.0.1.2</dns>
        <domain>dominio1.org</domain>
      </subnet>
      <subnet>
        <network>10.0.2.0/24</network>
        <range>
          <first>10.0.2.10</first>
          <last>10.0.2.20</last>
        </range>
        <router>10.0.2.1</router>
        <host name="Unicum" mac="AA:BB:CC:DD:EE:FF" ip="10.0.2.28"/>
      </subnet>
      <subnet>
        <network>10.0.0.0/30</network>
      </subnet>
    </server>
  </vm>

  <vm name="h1" type="dhcp3-isc">
    <client>
      <if>eth1</if>
    </client>
  </vm>

  <vm name="r2" type="dhcp3-isc">
    <relay>
      <toserver>10.0.0.1</toserver>
    </relay>
  </vm>

  <vm name="h2" type="dhcp3-isc">
    <client>
      <if>eth1</if>
    </client>
  </vm>

</dhcp_conf>
