=== davidfdezc/vnx/vnx-plugins/dhcp/dhcp.dtd
<!-- DHCP DTD version 1.0 -->
<!ELEMENT dhcp_conf (vm+)>

<!ELEMENT vm (server?,relay?,client?)>
<!ATTLIST vm name CDATA #REQUIRED
            type CDATA #REQUIRED>
            
<!ELEMENT server (subnet+)>
<!ELEMENT subnet (ip,range*,router*,dns*,domain?,host*)>

<!ELEMENT ip (#PCDATA)>
<!ATTLIST ip mask CDATA #REQUIRED>

<!ELEMENT range (first,last)>
<!ELEMENT first (#PCDATA)>
<!ELEMENT last (#PCDATA)>

<!ELEMENT router (#PCDATA)>

<!ELEMENT dns (#PCDATA)>

<!ELEMENT domain (#PCDATA)>

<!ELEMENT host (#PCDATA)>
<!ATTLIST host name CDATA #REQUIRED
               mac  CDATA #REQUIRED
               ip   CDATA #REQUIRED>




<!ELEMENT relay (toserver+)>
<!ELEMENT toserver (#PCDATA)>

<!ELEMENT client (if+)>
<!ELEMENT if (#PCDATA)>

=== davidfdezc/vnx/vnx-plugins/dhcp/examples/example_dhcp-plugin-conf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dhcp_conf SYSTEM "/usr/share/xml/vnx/dhcp.dtd">

<dhcp_conf>

  <vm name="r1" type="dhcp3-isc">
    <server>
      <subnet>
        <ip mask="24">10.0.1.0</ip>
        <range>
          <first>10.0.1.10</first>
          <last>10.0.1.20</last>
        </range>
        <router>10.0.1.1</router>
        <dns>10.0.1.2</dns>
        <domain>dominio1.org</domain>
      </subnet>
      <subnet>
        <ip mask="24">10.0.2.0</ip>
        <range>
          <first>10.0.2.10</first>
          <last>10.0.2.20</last>
        </range>
        <router>10.0.2.1</router>
        <host name="Unicum" mac="AA:BB:CC:DD:EE:FF" ip="10.0.2.28"/>
      </subnet>
    </server>
  </vm>

  <vm name="h1" type="dhcp3">
    <client>
      <if>1</if>
    </client>
  </vm>

  <vm name="r2" type="dhcp3">
    <relay>
      <toserver>10.0.0.1</toserver>
    </relay>
  </vm>

  <vm name="h2" type="dhcp3">
    <client>
      <if>1</if>
    </client>
  </vm>

</dhcp_conf>
