=== davidfdezc/vnx/vnx-plugins/ospf/ospf.dtd
<!-- OSPF DTD version 1.0 -->
<!ELEMENT ospf_conf (vm+)>
<!ELEMENT vm (zebra_bin?,ospfd_bin?,zebra,passive_if,network+)>
<!ATTLIST vm name CDATA #REQUIRED
                        type CDATA #REQUIRED
                        subtype CDATA #REQUIRED>
<!ELEMENT zebra_bin (#PCDATA)>
<!ELEMENT ospfd_bin (#PCDATA)>
<!ELEMENT zebra EMPTY>
<!ATTLIST zebra hostname CDATA #REQUIRED
                        password CDATA #REQUIRED>
<!ELEMENT passive_if (#PCDATA)>
<!ELEMENT network (ip,area)>
<!ELEMENT ip (#PCDATA)>
<!ATTLIST ip mask CDATA #REQUIRED>
<!ELEMENT area (#PCDATA)>

=== davidfdezc/vnx/vnx-plugins/ospf/examples/simple_ubuntu-ospf_conf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ospf_conf SYSTEM "/usr/share/xml/vnx/ospf.dtd">

<ospf_conf>

   <vm name="ubuntu" type="quagga" subtype="lib-install">
      <zebra hostname="vm1" password="xxxx"/>
      <network>
         <ip mask="32">10.0.50.1</ip>
         <area>0.0.0.0</area>
      </network>
      <network>
         <ip mask="30">10.0.0.0</ip>
         <area>0.0.0.0</area>
      </network>	
      <network>
         <ip mask="30">10.0.0.4</ip>
         <area>0.0.0.0</area>
      </network>	
   </vm>

</ospf_conf>
